using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

[assembly: AssemblyTitle("GnomeServer")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Gnome Server")]
[assembly: AssemblyCopyright("Copyright ©  2015")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("4dfedf14-70e9-4bab-a475-b7e13e805a48")]
[assembly: AssemblyVersion("2015.7.25.1749")]
[assembly: AssemblyFileVersion("2015.7.25.1749")]
